version: "3.0"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    ports:
      - 9200:9200
      - 9300:9300
    container_name: elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    ports:
      - 5601:5601
    container_name: kibana
    links:
      - elasticsearch:elasticsearch
